name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - gh-pages  # Vous pouvez changer cette branche si nécessaire

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # Dossier contenant les fichiers de votre site
